apiVersion: v1
kind: Pod
metadata:
  name: request-splitting-example
  labels:
    name: request-splitting-example
spec:
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: yeasy
    image: yeasy/simple-web
    ports: 
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
